import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import { BrowserRouter, Route, Routes, useOutletContext } from "react-router-dom";
import { Layout } from "@sylphx/leaf-theme-default";
import "@sylphx/leaf-theme-default/style.css";

// @ts-expect-error - Generated by Vite plugin
import { routes } from "virtual:reactpress/routes";
// @ts-expect-error - Generated by Vite plugin
import config from "virtual:leaf/config";

// Wrapper component to provide context
function RouteWrapper({ Component }: { Component: any }) {
	// Get TOC and docFooter from the component module
	const toc = Component.toc || [];
	const docFooter = Component.docFooter;

	return <Component />;
}

const rootElement = document.getElementById("root");

if (!rootElement) {
	throw new Error("Root element not found");
}

createRoot(rootElement).render(
	<StrictMode>
		<BrowserRouter>
			<Routes>
				<Route path="/" element={<Layout config={config} />}>
					{routes.map((route: any) => {
						const Component = route.component;
						const toc = Component.toc || [];
						const docFooter = Component.docFooter;

						return (
							<Route
								key={route.path}
								path={route.path === "/" ? undefined : route.path}
								index={route.path === "/"}
								element={<Component />}
								handle={{ toc, docFooter }}
							/>
						);
					})}
				</Route>
			</Routes>
		</BrowserRouter>
	</StrictMode>,
);
