import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import { createBrowserRouter, RouterProvider } from "react-router-dom";
import { Layout } from "@sylphx/leaf-theme-default";
import "@sylphx/leaf-theme-default/style.css";

// @ts-expect-error - Generated by Vite plugin
import { routes } from "virtual:reactpress/routes";
// @ts-expect-error - Generated by Vite plugin
import config from "virtual:leaf/config";

// Create router with data router API (required for useMatches)
const router = createBrowserRouter([
	{
		path: "/",
		element: <Layout config={config} />,
		children: routes.map((route: any) => {
			const Component = route.component;
			const toc = Component.toc || [];
			const docFooter = Component.docFooter;

			if (route.path === "/") {
				return {
					index: true,
					element: <Component />,
					handle: { toc, docFooter },
				};
			}

			return {
				path: route.path,
				element: <Component />,
				handle: { toc, docFooter },
			};
		}),
	},
]);

const rootElement = document.getElementById("root");

if (!rootElement) {
	throw new Error("Root element not found");
}

createRoot(rootElement).render(
	<StrictMode>
		<RouterProvider router={router} />
	</StrictMode>,
);
