import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import { BrowserRouter, Route, Routes } from "react-router-dom";
import { Layout } from "@sylphx/leaf-theme-default";
import "@sylphx/leaf-theme-default/style.css";

// @ts-expect-error - Generated by Vite plugin
import { routes } from "virtual:reactpress/routes";
import config from "./config.json";

const rootElement = document.getElementById("root");

if (!rootElement) {
	throw new Error("Root element not found");
}

createRoot(rootElement).render(
	<StrictMode>
		<BrowserRouter>
			<Routes>
				<Route path="/" element={<Layout config={config} />}>
					{routes.map((route: any) => {
						const Component = route.component;
						return (
							<Route
								key={route.path}
								path={route.path === "/" ? undefined : route.path}
								index={route.path === "/"}
								element={<Component />}
							/>
						);
					})}
				</Route>
			</Routes>
		</BrowserRouter>
	</StrictMode>,
);
